### PR TITLE
Downgrade lychee action to 1.5.3

### PR DESCRIPTION
**Pull request by lechnerc77**
There seems to be an issue with the lychee action in version 1.5.4 and links to Twitter that constantly time out. 
This issue is not present in version 1.5.3, so this pull request provides the code to downgrade the version accordingly. 

This should resolve the issue #381 with the timeout errors

### CODE REVIEW

**Comment by lechnerc77** [comment]
Also opened an issue for this scenario in the repository of the [GitHub Action](https://github.com/lycheeverse/lychee-action/issues/178)

**Review by marcduiker — APPROVED** [review]
LGTM

**Comment by marcduiker** [comment]
Doesn't look to be resolved with 1.5.3 :/. Or could it be related to a cached (error) result?

**Comment by lechnerc77** [comment]
Looks weird now:

The original GH Action run worked with 1.5.3. I tried it with the 1.5.4 again in my [sandbox repo](https://github.com/lechnerc77/test-lychee-twitter/actions/runs/3861770300/jobs/6582935159) and now it worked without timeout. While the previous run showed the [timeouts](https://github.com/lechnerc77/test-lychee-twitter/actions/runs/3861505057).

This seems to be an issue between the GH Action runner and Twitter (and my hot bet is Twitter). 

I would propose to close the PR as it does not solve the issue as I expected.

**Comment by marcduiker** [comment]
Yes, it's suspicious that it's limited to Twitter 🧐. Ok, I'll close this one.

**Comment by lechnerc77** [comment]
@marcduiker : Interesting additional info how things work with twitter links specifically: [link](https://github.com/lycheeverse/lychee-action/issues/178#issuecomment-1374829092)

**Pull request closed without merging**
